### ISSUE TITLE
Redirects system via file

### ISSUE THREAD

**Issue by kltm** [geneontology/web-gocam#10]
As the domain root, the current Drupal maintains a larger number of redirect, both to external resources, legacy page updates, and page renamings.; the webserver that hosts it likely many more.
While we will likely get rid of many of these, we will still have many cases where we'll want to redirect in various ways, some of them supporting this legacy.

This would be to implement a redirect system built into the new site's deployment, that reads from a structured file and redirects accordingly, editable by general GO users.

As a model, note the github.io system and https://github.com/jekyll/jekyll-redirect-from ; these could be directly used depending on the deployment method.

**Comment by kltm** [comment]
It may be that we just end up doing a bunch with apache.

**Comment by kltm** [comment]
This may be in place with a different system?

**Comment by lpalbou** [comment]
@kltm the redirect system you mentioned here seems to be for the go site (https://github.com/geneontology/go-site/issues/959), not for the gocam site, hence I think the question on wether this is the right tracker for this ticket

**Comment by kltm** [comment]
Working with @cmungall , I believe that we have the critical mappings in place? See: https://github.com/geneontology/operations/blob/master/ansible/root-domain-head-up.yml#L30

**Comment by cmungall** [comment]
Yep

>
