### ISSUE TITLE
Technical planning: Handover of GO-CAM site

### ISSUE THREAD

**Issue by lpalbou** [geneontology/web-gocam#15]
@kltm @tmushayahama .

Two possibilities:
1) transfer the site to a bucket under geneontology.org (AWS route 53 DNS record) and continue to deploy there; would solve the .cloud issue instead of .org @kltm 
2) OR create a web component to browse GO-CAMs with @tmushayahama (also good for training)

@cmungall to decide.

**Comment by cmungall** [comment]
We should do 1 anyway, and then 2 as a stretch goal

**Comment by lpalbou** [comment]
Got it. @kltm ping me on slack when you have about 1h and we should be able to get that done without too much trouble.

**Comment by kltm** [comment]
Talking with @cmungall , we were thinking of having @dustine32 and @tmushayahama take the lead on this (combined with #16
).

**Comment by tmushayahama** [comment]
@cmungall @lpalbou as for 2) I would like more discussion and create the web component using the search API (on landing page) than plane Sparql Queries used on GO cam site. So I would go with 1)

**Comment by lpalbou** [comment]
To avoid cross discussions and the spread of multiple different opinions (I also have one ;) ), let's discuss this this Thursday and create an action item for this where we all agree. On https://github.com/geneontology/web-gocam/issues/16, I discussed that I believe @kltm should probably be the lead on that (for step 1: transfer to bbop AWS & use of go domain), but to create a web component & integrate on the GO site, it could indeed be @tmushayahama . In which case, yes of course Tremayne we'll need to discuss more; I am even thinking of Xtreme programming, so that it serves also as a training on those techs.

**Comment by kltm** [comment]
Talking to @tmushayahama and @cmungall , @tmushayahama , you now have the go ahead to make an attempt to see how this looks.

**Comment by kltm** [comment]
Handover complete
