### ISSUE TITLE
External links should go to new AmiGO GO-CAM pages

### ISSUE THREAD

**Issue by kltm** [geneontology/web-gocam#23]
This would be a fully fixed version of https://github.com/geneontology/web-gocam/issues/21#issuecomment-1273876159

Some links at external locations point to the noctua curation system, creating load and outages for something that is not meant to be a public interface. An example (the only one?) is the pathway widget, which routes to a noctua view.

This would be closed when user all traffic associated with this repo is directed away from noctua (in conjunction with https://github.com/geneontology/api-gorest-2021/issues/6).

**Comment by kltm** [comment]
On discussion, closing this ticket would be:

- [ ] listing all external traffic coming in to noctua, barista, and minerva
- [ ] creating a ticket/plan for each separate source or strategy

**Comment by kltm** [comment]
In discussion with @vanaukenk and @ukemi , @kltm will

- [ ] update model URI
- [ ] do a doc check

Otherwise, we'll take this as bugs and and fix as we find them as part of ongoing maintenance.

**Comment by vanaukenk** [comment]
See also:  https://agr-jira.atlassian.net/browse/SCRUM-3157

**Comment by kltm** [comment]
I'm having a little trouble building the code on prod. Likely caused by an older node/npm; will be digging into it.

**Comment by kltm** [comment]
After initially running into this error after a wipe and build
```
[13:22:04] 'compile_js_dev' errored after 35 ms
[13:22:04] TypeError: Cannot read property 'value' of undefined
    at /home/bbop/local/src/git/amigo/gulpfile.js:322:45
    at new Promise (<anonymous>)
    at _client_compile_task (/home/bbop/local/src/git/amigo/gulpfile.js:297:12)
    at /home/bbop/local/src/git/amigo/gulpfile.js:345:20
    at Function._.map._.collect (/home/bbop/local/src/git/amigo/node_modules/underscore/underscore.js:172:24)
    at compile_js_dev (/home/bbop/local/src/git/amigo/gulpfile.js:344:12)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/home/bbop/local/src/git/amigo/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
[13:22:04] 'install' errored after 5.46 s
```
I was able to proceed with a second run of the command. All further wipe and build have not recreated this error, so there is some state I missed or the error is non-deterministic. Either way, pushing forward.

**Comment by kltm** [comment]
I jumped the gun on putting this out to production: we will need to have the updated code in the merged GO API out first.

**Comment by tmushayahama** [comment]
just from top of my head, bbop gulp doesn't work for node more than 10

**Comment by kltm** [comment]
Fortunately, it seems to be a non-deterministic issue. The patch-up that @pkalita-lbl did allows us to compile on some of the older versions, including production. The issues we have now are with me jumping the gun on the API, not that we've switched to HTTPS.

**Comment by kltm** [comment]
http://model.geneontology.org/568b0f9600000284 should go to https://amigo.geneontology.org/amigo/model/568b0f9600000284

**Comment by kltm** [comment]
This now seems to function as expected.
