### ISSUE TITLE
Remove GO-CAM download card from /go-cam site

### ISSUE THREAD

**Issue by kltm** [geneontology/web-gocam#24]
Remove GO-CAM download card from /go-cam site--the current one seems to contain items last updated in Dec 2020. As well, we are having a discussion about whether we are wanting to continue with the current SIF and JSON blob. After a discussion with @dustine32 , we believe it would be easier to re-implement (using existing or new code) than to fix. Adding new functionality with "fixed" downloads would be a different item. (Tagging @pgaudet and @cmungall ).

**Comment by kltm** [comment]
@dustine32 I've gone ahead and merged. I'm not sure I have permissions; could you add me or run `ng build` and then `deploy.sh`?

**Comment by dustine32** [comment]
@kltm Done! Thank you for handling this!

**Comment by kltm** [comment]
Fast and easy--cheers!

**Comment by kltm** [comment]
Remove lines that refer to previously available downloads.

**Comment by kltm** [comment]
@dustine32 Could you add me or run `ng build` and then `deploy.sh` for me?

**Comment by dustine32** [comment]
@kltm Yep, no prob. I just deployed your change!

**Comment by kltm** [comment]
@dustine32 Cheers--looking good now!
