### ISSUE TITLE
SIF Archive Download

### ISSUE THREAD

**Issue by lpalbou** [geneontology/web-gocam#7]
Ability to download GOCAMs in SIF format:
- [ ] : create either SPARQL or GOLR queries to fetch each gocam as a graph
- [ ] : convert the graph in SIF format
- [ ] : integrate the code or queries in the pipeline to produce an archive of all gocams in SIF

**Comment by kltm** [comment]
See item https://github.com/geneontology/pipeline/issues/51

**Comment by lpalbou** [comment]
Solved with this repo: https://github.com/geneontology/gocam-sif-pyexport
