### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lpalbou** [geneontology/web-gocam#9]
The current Feedback component does not create GitHub tickets and there are discussions about using a 3rd party tool for handling feedbacks.
- [x] : Check if API to submit ticket to GitHub (yes: https://developer.github.com/v3/issues/)
- [ ] : Monitor discussion on other choices (e.g. tender)

**Comment by kltm** [comment]
@lpalbou I'll fold this into a new feedback component issue for the public website project.

**Comment by kltm** [comment]
Apologies--this is on me.

**Comment by kltm** [comment]
now dupe of https://github.com/geneontology/go-site/issues/750
